name: duan_antam
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  
  # --- CÁC THƯ VIỆN ĐÃ THÊM MỚI ---
  firebase_core: ^2.24.2       # Cốt lõi để chạy Firebase
  cloud_firestore: ^4.14.0     # Cơ sở dữ liệu lưu lịch thuốc
  url_launcher: ^6.2.1         # Để thực hiện gọi điện thoại
  intl: ^0.19.0                # Để định dạng ngày giờ (8:00, 17/12...)
  # ------------------------------

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # fonts: 
  #   - family: Arimo ... (Nếu bạn đã tải font thì bỏ comment phần này)